config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments
    resources :images
  end
  
  namespace :admin do
    resources :posts do 
      resources :comments
      resources :images
    end
  end

  devise_for :users,
  controllers: {
    registrations: :registrations,
    sessions: :sessions
  },
  defaults: { format: :json }

  namespace :api do
    namespace :v1 do
      namespace :admin do
        resources :posts do 
          resources :comments
          resources :images
        end
      end
      resources :posts do 
        resources :comments
        resources :images
      end
    end
  end

  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy

    has_many_attached :images

    def image_urls
        images.map{|i| Rails.application.routes.url_helpers.url_for(i) }
    end
    
    validates :title, presence: true,
                        length: {minimum: 3, maximum: 100}

end

app/controllers/admin/posts_controller.rb
#encoding: utf-8

class Admin::PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
    before_action :require_admin
    #before_action :authenticate_user!, except: [:index, :show]
  
    def require_admin
        unless user_signed_in? && current_user.admin?
            redirect_to root_path, notice: "You are not authorized to perform this action."
        end
    end
    # GET /posts or /posts.json
    def index
      @posts = Post.all
      authorize @posts
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Posts: #{@posts.count}", template: "admin/posts/index.html.erb", layout: 'pdf'  # Excluding ".pdf" extension.
        end
      end
    end
  
    # GET /posts/1 or /posts/1.json
    def show
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Post id: #{@post.id}", template: "admin/posts/pdf.html.erb", layout: 'pdf'
        end
      end
    end
  
    # GET /posts/new
    def new
      #if current_user.admin
        @post = Post.new
        authorize @post
      #else
       # redirect_to posts_path, notice: "Not Authorized User"
      #end 
    end
  
    # GET /posts/1/edit
    def edit
        #redirect_to @post, notice: "Not Authorized User" if current_user.admin == false 
    end
  
    # POST /posts or /posts.json
    def create
      @post = Post.new(post_params)
      authorize @post
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to admin_post_path(@post), notice: "Post was successfully created.admin" }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to admin_post_path(@post), notice: "Post was successfully updated.admin" }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /posts/1 or /posts/1.json
    def destroy
      #if current_user.admin
        @post.destroy
        respond_to do |format|
          format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
          format.json { head :no_content }
        end
      #else
        #redirect_to posts_url, notice: "Not authorized user"
      #end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :body, images: [])
      end
  end
  

app/controllers/api/v1/admin/posts_controller.rb
#encoding: utf-8

class Api::V1::Admin::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, except: [:index, :show]
  before_action :require_admin

  def require_admin
    if !signed_in? || !current_user.admin?
      render json: { errors: { 'err' => "You are not authorized to perform this action" } }, status: :unprocessable_entity
    end
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    #authorize @posts

    render json: @posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    render json: @post
  end

  # GET /posts/new
  # def new
  #   #if current_user.admin
  #     @post = Post.new
  #     #authorize @post
  #   #else
  #    # redirect_to posts_path, notice: "Not Authorized User"
  #   #end 
  # end

  def create
    @post = Post.new(post_params)
    authorize @post

    if @post.save
      render json: @post, status: :created, location: api_v1_posts_path(@post), methods: [:image_urls]
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  def update
    authorize @post

    if @post.update(post_params)
      render json: @post, status: :ok, location: api_v1_posts_path(@post) 
    else
      render json: @post.errors, status: :unprocessable_entity 
    end
  end

  def destroy 
    authorize @post
    @post.destroy
    if @response
      render json: @response
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, images: [])
    end

end

app/controllers/api/v1/posts_controller.rb
#encoding: utf-8

class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :require_admin

  # def require_admin
  #   unless api_v1_user_signed_in? && !current_api_v1_user.admin?
  #       redirect_to root_path, notice: "You are not authorized to perform this action."
  #   end
  # end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    #authorize @posts

    render json: @posts, methods: [:image_urls]
  end

  # GET /posts/1 or /posts/1.json
  def show
    render json: @post
  end

  # GET /posts/new
  # def new
  #   #if current_user.admin
  #     @post = Post.new
  #     #authorize @post
  #   #else
  #    # redirect_to posts_path, notice: "Not Authorized User"
  #   #end 
  # end

  def create
    @post = Post.new(post_params)
    authorize @post

    if @post.save
      render json: @post, status: :created, location: api_v1_posts_path(@post)
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  def update
    authorize @post

    if @post.update(post_params)
      render json: @post, status: :ok, location: api_v1_posts_path(@post) 
    else
      render json: @post.errors, status: :unprocessable_entity 
    end
  end

  def destroy 
    authorize @post
    @post.destroy
    if @response
      render json: @response
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, images: [])
    end

end

app/controllers/posts_controller.rb
#encoding: utf-8

class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    authorize @posts
    if user_signed_in? && current_user.admin?
      redirect_to admin_posts_path
    end
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Posts: #{@posts.count}", template: "posts/index.html.erb", layout: 'pdf'   # Excluding ".pdf" extension.
      end
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Post id: #{@post.id}", template: "posts/show.html.erb", layout: 'pdf'   # Excluding ".pdf" extension.
      end
    end
  end

  # GET /posts/new
  def new
    #if current_user.admin
      @post = Post.new
      authorize @post
    #else
     # redirect_to posts_path, notice: "Not Authorized User"
    #end 
  end

  # GET /posts/1/edit
  def edit
      redirect_to @post, notice: "Not Authorized User"      
  end

  def destroy
    #if current_user.admin
      @post.destroy
      respond_to do |format|
        format.html { redirect_to admin_posts_path, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    #else
      #redirect_to posts_url, notice: "Not authorized user"
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>-->
        <% post.errors.each do |error| %>
          <div class="alert alert-danger alert-dismissible" role="alert">
              <%= error.full_message %> 
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="field mb-3">
    <%= form.text_area :body, class: "form-control", placeholder: "Content" %>
  </div>

  <div class="field mb-3">
    <%= form.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', admin_post_path(@post), class: "btn btn-secondary mt-2" %> 
<%= link_to 'Back', admin_posts_path, class: "btn btn-dark mt-2" %>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <div class="card w-75 mb-3">
    <div class="card-body">
      
        <h5 class="card-title"> <%= post.title %> </h5>
        <p class="card-text"> <%= post.body %> </p>
        <%= link_to 'Read more', admin_post_path(post), class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

<%= link_to 'Create PDF', admin_posts_path(format: :pdf), class: "btn btn-dark", target: :_blank %>
<br />
<br />

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', admin_posts_path, class: "btn btn-dark mt-2" %>

app/views/admin/posts/pdf.html.erb
<div class="card w-75">
  <div class="card-body">
    <h5 class="card-title"> <%= @post.title %> </h5>
    <p class="card-text"> <%= @post.body %> </p>

    <div class="row page-break">
      <%  @post.images.each do |image| %>
        <div class="col-lg-4 col-md-12 mb-4">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <%= image_tag(image, style: 'width:100%; height:auto') %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br />
<%= render 'comments/pdf_index' %>

app/views/admin/posts/show.html.erb
<div class="card w-75">
  <div class="card-body">
    <h5 class="card-title"> <%= @post.title %> </h5>
    <p class="card-text"> <%= @post.body %> </p>

    <div class="row">
      <%  @post.images.each do |image| %>
        <div class="col-lg-4 col-md-12 mb-4">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <%= image_tag(image, style: 'width:100%; height:auto') %>
          </div>
        </div>
      <% end %>
    </div>

    <%= link_to 'Edit', edit_admin_post_path(@post), class: "btn btn-secondary" %> 
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%= link_to 'Back', admin_posts_path, class: "btn btn-dark" %>
    <%= link_to 'Create PDF', admin_post_path(@post, format: :pdf), class: "btn btn-dark", target: :_blank %>
  </div>
</div>

<br />
<%= render 'admin/comments/index' %>
<br />
<%= render 'admin/comments/new' %>