config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments
    resources :images
  end
  
  namespace :admin do
    resources :posts do 
      resources :comments
      resources :images
    end
  end

  devise_for :users,
  controllers: {
    registrations: :registrations,
    sessions: :sessions
  },
  defaults: { format: :json }

  namespace :api do
    namespace :v1 do
      namespace :admin do
        resources :posts do 
          resources :comments
          resources :images
        end
      end
      resources :posts do 
        resources :comments
        resources :images
      end
    end
  end

  root 'posts#index'
end

app/views/admin/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!--<a class="navbar-brand" href="posts">Blog</a>-->
    <%= link_to 'Blog', admin_posts_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', admin_posts_path , class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', admin_posts_path , class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path , class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path , class: "nav-link" %>
          </li>
        <% end %>  
      </ul>
      <% if current_user && current_user.admin %>
        <form class="d-flex">
          <%= link_to 'Create new post', new_admin_post_path , class: "btn btn-outline-success" %>
        </form>
      <% end %>
    </div>
  </div>
</nav>